import { useEffect, useState } from "react";
import { BiEdit, BiPlus, BiX } from "react-icons/bi";
import MainLayout from "../layouts/MainLayout";
import { createSuperAdminUser, getOrganizations, getSuperAdminUsers, getSystemRoles, updateSuperAdminUser } from "../services/superAdminService";

const blank = { first_name:"", last_name:"", email:"", password:"", role:"Viewer", organization_id:"", is_active:true };

export default function SuperAdminUsers() {
  const [users,setUsers]=useState([]),[orgs,setOrgs]=useState([]),[roles,setRoles]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const load=async()=>{try{setLoading(true);const [u,o,r]=await Promise.all([getSuperAdminUsers(),getOrganizations(),getSystemRoles()]);setUsers(u?.data||[]);setOrgs(o?.data||[]);setRoles(r?.data||[])}catch(e){setError(e.response?.data?.detail||"Failed to load users.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{const payload={...form,organization_id:form.organization_id||null};if(editing){if(!payload.password)delete payload.password;await updateSuperAdminUser(editing.id,payload)}else await createSuperAdminUser(payload);setOpen(false);setEditing(null);setForm(blank);await load()}catch(e){setError(e.response?.data?.detail||"Unable to save user.")}finally{setSaving(false)}};
  const edit=row=>{setEditing(row);setForm({first_name:row.first_name,last_name:row.last_name,email:row.email,password:"",role:row.role||"Viewer",organization_id:row.organization_id||"",is_active:row.is_active});setOpen(true)};
  return <MainLayout><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold text-gray-900">System Users</h1><p className="mt-1 text-gray-500">Manage users across all organizations.</p></div><button onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700"><BiPlus/> Add User</button></div>
  {error&&<div className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-400"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Organization</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Action</th></tr></thead><tbody>{users.map(row=><tr key={row.id} className="border-t border-gray-100"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{row.first_name} {row.last_name}</p><p className="text-xs text-gray-500">{row.email}</p></td><td className="px-5 py-4 text-sm text-gray-600">{row.organization_name||"System level"}</td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{row.role}</span></td><td className="px-5 py-4 text-sm">{row.is_active?"Active":"Inactive"}</td><td className="px-5 py-4"><button onClick={()=>edit(row)} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><BiEdit size={19}/></button></td></tr>)}{!loading&&!users.length&&<tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">No users found.</td></tr>}</tbody></table></div></div>
  {open&&<div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-gray-100 px-6 py-5"><h2 className="text-xl font-bold text-slate-800">{editing?"Edit User":"Create User"}</h2><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100"><BiX size={22}/></button></div><form onSubmit={submit} className="grid grid-cols-1 gap-4 p-6 sm:grid-cols-2"><input required className="rounded-xl border px-4 py-3" placeholder="First name" value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/><input required className="rounded-xl border px-4 py-3" placeholder="Last name" value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/><input required type="email" className="rounded-xl border px-4 py-3 sm:col-span-2" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required={!editing} type="password" className="rounded-xl border px-4 py-3 sm:col-span-2" placeholder={editing?"New password (optional)":"Password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select required className="rounded-xl border px-4 py-3" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.filter(r=>r.name.trim().toLowerCase()!=="super admin").map(r=><option key={r.id}>{r.name}</option>)}</select><select required className="rounded-xl border px-4 py-3" value={form.organization_id} onChange={e=>setForm({...form,organization_id:e.target.value})}><option value="">Select organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><label className="flex items-center gap-2 text-sm text-gray-600"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active account</label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3 font-semibold text-gray-600">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?"Saving...":"Save User"}</button></div></form></div></div>}</MainLayout>;
}
