"""connect approvals to amendments

Revision ID: c6eb950bb691
Revises: 3430edf9b741
Create Date: 2026-08-17 00:24:32.799038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6eb950bb691'
down_revision: Union[str, Sequence[str], None] = '3430edf9b741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('amendment_id', sa.UUID(), nullable=True))
    op.alter_column('approvals', 'contract_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_approvals_amendment_id'), 'approvals', ['amendment_id'], unique=False)
    op.create_foreign_key(None, 'approvals', 'amendments', ['amendment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_index(op.f('ix_approvals_amendment_id'), table_name='approvals')
    op.alter_column('approvals', 'contract_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('approvals', 'amendment_id')
    # ### end Alembic commands ###
