"""create approvals

Revision ID: e4cf80878832
Revises: a6d6944
Create Date: 2026-08-13 03:17:15.230340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cf80878832'
down_revision: Union[str, Sequence[str], None] = 'a6d6944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_approver_id'), 'approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approvals_contract_id'), 'approvals', ['contract_id'], unique=False)
    op.create_index(op.f('ix_approvals_organization_id'), 'approvals', ['organization_id'], unique=False)
    op.drop_constraint(op.f('contract_types_name_key'), 'contract_types', type_='unique')
    op.drop_constraint(op.f('fk_contract_types_organization_id'), 'contract_types', type_='foreignkey')
    op.create_foreign_key(None, 'contract_types', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(op.f('fk_contracts_organization_id'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(op.f('organizations_code_key'), 'organizations', type_='unique')
    op.drop_constraint(op.f('fk_parties_organization_id'), 'parties', type_='foreignkey')
    op.create_foreign_key(None, 'parties', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_users_organization_id'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_organization_id'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.create_foreign_key(op.f('fk_parties_organization_id'), 'parties', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('organizations_code_key'), 'organizations', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contracts_organization_id'), 'contracts', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'contract_types', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contract_types_organization_id'), 'contract_types', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('contract_types_name_key'), 'contract_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_approvals_organization_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_contract_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approver_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
