from uuid import UUID
from datetime import date, datetime

from pydantic import BaseModel, Field


# ============================================================
# CREATE MILESTONE
# ============================================================

class MilestoneCreate(BaseModel):

    contract_id: UUID

    # AUTO-GENERATED BY BACKEND
    milestone_no: str | None = None

    title: str = Field(
        min_length=1,
        max_length=150,
    )

    description: str | None = Field(
        default=None,
        max_length=2000,
    )

    due_date: date | None = None


# ============================================================
# UPDATE MILESTONE
# ============================================================

class MilestoneUpdate(BaseModel):

    title: str | None = Field(
        default=None,
        min_length=1,
        max_length=150,
    )

    description: str | None = Field(
        default=None,
        max_length=2000,
    )

    due_date: date | None = None


# ============================================================
# CREATE MILESTONE TASK
# ============================================================

class MilestoneTaskCreate(BaseModel):

    title: str = Field(
        min_length=1,
        max_length=255,
    )

    description: str | None = Field(
        default=None,
        max_length=2000,
    )


# ============================================================
# UPDATE MILESTONE TASK
# ============================================================

class MilestoneTaskUpdate(BaseModel):

    title: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
    )

    description: str | None = Field(
        default=None,
        max_length=2000,
    )

    is_completed: bool | None = None


# ============================================================
# MILESTONE TASK RESPONSE
# ============================================================

class MilestoneTaskResponse(BaseModel):

    id: UUID

    milestone_id: UUID

    title: str

    description: str | None = None

    is_completed: bool

    completed_at: datetime | None = None

    created_at: datetime | None = None

    updated_at: datetime | None = None

    model_config = {
        "from_attributes": True,
    }


# ============================================================
# RESPONSE
# ============================================================

class MilestoneResponse(BaseModel):

    id: UUID

    organization_id: UUID

    contract_id: UUID

    milestone_no: str

    title: str

    description: str | None = None

    due_date: date | None = None

    # SYSTEM-CALCULATED
    progress: int

    # SYSTEM-CALCULATED
    status: str

    is_archived: bool = False

    created_at: datetime | None = None

    updated_at: datetime | None = None

    contract_no: str | None = None

    contract_title: str | None = None

    tasks: list[MilestoneTaskResponse] = []

    model_config = {
        "from_attributes": True,
    }